python evaluation/model_train_eval.py --config_name=ml_canzian --pred_target=dep_weekly --eval_task=single --demographic_feature=$1 --demographic_label=$2
python evaluation/model_train_eval.py --config_name=ml_farhan --pred_target=dep_weekly --eval_task=single --demographic_feature=$1 --demographic_label=$2
python evaluation/model_train_eval.py --config_name=ml_lu --pred_target=dep_weekly --eval_task=single --demographic_feature=$1 --demographic_label=$2
python evaluation/model_train_eval.py --config_name=ml_saeb --pred_target=dep_weekly --eval_task=single --demographic_feature=$1 --demographic_label=$2
python evaluation/model_train_eval.py --config_name=ml_wahle --pred_target=dep_weekly --eval_task=single --demographic_feature=$1 --demographic_label=$2
python evaluation/model_train_eval.py --config_name=ml_chikersal --pred_target=dep_weekly --eval_task=single --demographic_feature=$1 --demographic_label=$2
python evaluation/model_train_eval.py --config_name=ml_wang --pred_target=dep_weekly --eval_task=single --demographic_feature=$1 --demographic_label=$2
python evaluation/model_train_eval.py --config_name=ml_xu_interpretable --pred_target=dep_weekly --eval_task=single --demographic_feature=$1 --demographic_label=$2
python evaluation/model_train_eval.py --config_name=ml_xu_personalized --pred_target=dep_weekly --eval_task=single --demographic_feature=$1 --demographic_label=$2
