{feature_definition: {empty_feature_filtering_th: 0.9, feature_list: ['f_loc:phone_locations_barnett_disttravelled:14dhist',
      'f_loc:phone_locations_barnett_maxdiam:14dhist', 'f_loc:phone_locations_barnett_rog:14dhist',
      'f_loc:phone_locations_barnett_stdflightlen:14dhist', 'f_loc:phone_locations_barnett_maxhomedist:14dhist',
      'f_loc:phone_locations_doryab_numberofsignificantplaces:14dhist', 'f_loc:phone_locations_barnett_circdnrtn:14dhist',
      is_sensitive], feature_list_more_feat_types: ['f_loc:phone_locations_barnett_disttravelled:14dhist',
      'f_loc:phone_locations_barnett_maxdiam:14dhist', 'f_loc:phone_locations_barnett_rog:14dhist',
      'f_loc:phone_locations_barnett_stdflightlen:14dhist', 'f_loc:phone_locations_barnett_maxhomedist:14dhist',
      'f_loc:phone_locations_doryab_numberofsignificantplaces:14dhist', 'f_loc:phone_locations_barnett_circdnrtn:14dhist',
      is_sensitive], include_device_type: false, use_norm_features: false}, name: ml_canzian,
  training_params: {save_and_reload: false, verbose: 0}}
