{feature_definition: {empty_feature_filtering_th: 0.9, feature_list: ['f_loc:phone_locations_doryab_loglocationvariance:14dhist',
      'f_loc:phone_locations_doryab_movingtostaticratio:14dhist', 'f_loc:phone_locations_barnett_disttravelled:14dhist',
      'f_loc:phone_locations_doryab_avgspeed:14dhist', 'f_loc:phone_locations_doryab_numberofsignificantplaces:14dhist',
      'f_loc:phone_locations_doryab_locationentropy:14dhist', 'f_loc:phone_locations_doryab_normalizedlocationentropy:14dhist',
      'f_loc:phone_locations_barnett_hometime:14dhist', 'f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:14dhist',
      'f_steps:fitbit_steps_intraday_rapids_sumdurationsedentarybout:14dhist', is_sensitive],
    feature_list_more_feat_types: ['f_loc:phone_locations_doryab_loglocationvariance:14dhist',
      'f_loc:phone_locations_doryab_movingtostaticratio:14dhist', 'f_loc:phone_locations_barnett_disttravelled:14dhist',
      'f_loc:phone_locations_doryab_avgspeed:14dhist', 'f_loc:phone_locations_doryab_numberofsignificantplaces:14dhist',
      'f_loc:phone_locations_doryab_locationentropy:14dhist', 'f_loc:phone_locations_doryab_normalizedlocationentropy:14dhist',
      'f_loc:phone_locations_barnett_hometime:14dhist', 'f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout:14dhist',
      'f_steps:fitbit_steps_intraday_rapids_sumdurationsedentarybout:14dhist', is_sensitive],
    include_device_type: true, use_norm_features: false}, name: ml_farhan, training_params: {
    save_and_reload: false, verbose: 0}}
