{feature_definition: {empty_feature_filtering_th: 0.9, feature_list_base: ['f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout',
      'f_loc:phone_locations_barnett_hometime', 'f_loc:phone_locations_barnett_maxdiam',
      'f_loc:phone_locations_barnett_disttravelled', 'f_loc:phone_locations_doryab_loglocationvariance',
      'f_screen:phone_screen_rapids_sumdurationunlock', is_sensitive], feature_list_more_feat_types_base: [
      'f_steps:fitbit_steps_intraday_rapids_sumdurationactivebout', 'f_loc:phone_locations_barnett_hometime',
      'f_loc:phone_locations_barnett_maxdiam', 'f_loc:phone_locations_barnett_disttravelled',
      'f_loc:phone_locations_doryab_loglocationvariance', 'f_screen:phone_screen_rapids_sumdurationunlock',
      'f_call:phone_calls_rapids_incoming_count', 'f_call:phone_calls_rapids_outgoing_count',
      is_sensitive], include_device_type: false, use_norm_features: false}, name: ml_wahle,
  training_params: {save_and_reload: false, verbose: 0}}
