{feature_definition: {empty_feature_filtering_th: 0.5, feature_list_base: ['f_screen:phone_screen_rapids_avgdurationunlock',
      'f_screen:phone_screen_rapids_stddurationunlock', 'f_screen:phone_screen_rapids_countepisodeunlock',
      'f_screen:phone_screen_rapids_sumdurationunlock', 'f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain',
      'f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain', 'f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain',
      'f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain', 'f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain',
      'f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain', 'f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout',
      'f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout', 'f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout',
      'f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout', 'f_steps:fitbit_steps_intraday_rapids_sumsteps',
      'f_loc:phone_locations_barnett_circdnrtn', 'f_loc:phone_locations_doryab_timeathome',
      'f_loc:phone_locations_doryab_locationentropy', 'f_loc:phone_locations_doryab_loglocationvariance',
      'f_loc:phone_locations_doryab_avglengthstayatclusters', 'f_loc:phone_locations_doryab_movingtostaticratio',
      'f_loc:phone_locations_doryab_numberlocationtransitions', 'f_loc:phone_locations_doryab_numberofsignificantplaces',
      'f_loc:phone_locations_doryab_outlierstimepercent', 'f_loc:phone_locations_doryab_radiusgyration',
      'f_loc:phone_locations_doryab_totaldistance', 'f_loc:phone_locations_locmap_duration_in_locmap_study',
      'f_loc:phone_locations_locmap_percent_in_locmap_study', 'f_loc:phone_locations_locmap_duration_in_locmap_exercise',
      'f_loc:phone_locations_locmap_percent_in_locmap_exercise', 'f_loc:phone_locations_locmap_duration_in_locmap_greens',
      'f_loc:phone_locations_locmap_percent_in_locmap_greens', is_sensitive], feature_list_more_feat_types_base: [
      'f_screen:phone_screen_rapids_avgdurationunlock', 'f_screen:phone_screen_rapids_stddurationunlock',
      'f_screen:phone_screen_rapids_countepisodeunlock', 'f_screen:phone_screen_rapids_sumdurationunlock',
      'f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain', 'f_slp:fitbit_sleep_intraday_rapids_countepisodeasleepunifiedmain',
      'f_slp:fitbit_sleep_intraday_rapids_countepisodeawakeunifiedmain', 'f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain',
      'f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain', 'f_slp:fitbit_sleep_intraday_rapids_sumdurationawakeunifiedmain',
      'f_steps:fitbit_steps_intraday_rapids_avgdurationactivebout', 'f_steps:fitbit_steps_intraday_rapids_avgdurationsedentarybout',
      'f_steps:fitbit_steps_intraday_rapids_countepisodeactivebout', 'f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout',
      'f_steps:fitbit_steps_intraday_rapids_sumsteps', 'f_loc:phone_locations_barnett_circdnrtn',
      'f_loc:phone_locations_doryab_timeathome', 'f_loc:phone_locations_doryab_locationentropy',
      'f_loc:phone_locations_doryab_loglocationvariance', 'f_loc:phone_locations_doryab_avglengthstayatclusters',
      'f_loc:phone_locations_doryab_movingtostaticratio', 'f_loc:phone_locations_doryab_numberlocationtransitions',
      'f_loc:phone_locations_doryab_numberofsignificantplaces', 'f_loc:phone_locations_doryab_outlierstimepercent',
      'f_loc:phone_locations_doryab_radiusgyration', 'f_loc:phone_locations_doryab_totaldistance',
      'f_loc:phone_locations_locmap_duration_in_locmap_study', 'f_loc:phone_locations_locmap_percent_in_locmap_study',
      'f_loc:phone_locations_locmap_duration_in_locmap_exercise', 'f_loc:phone_locations_locmap_percent_in_locmap_exercise',
      'f_loc:phone_locations_locmap_duration_in_locmap_greens', 'f_loc:phone_locations_locmap_percent_in_locmap_greens',
      'f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetothers',
      'f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetown',
      'f_blue:phone_bluetooth_doryab_meanscansothers', 'f_blue:phone_bluetooth_doryab_meanscansown',
      'f_blue:phone_bluetooth_doryab_uniquedevicesothers', 'f_blue:phone_bluetooth_doryab_uniquedevicesown',
      'f_call:phone_calls_rapids_incoming_count', 'f_call:phone_calls_rapids_incoming_distinctcontacts',
      'f_call:phone_calls_rapids_incoming_sumduration', 'f_call:phone_calls_rapids_missed_count',
      'f_call:phone_calls_rapids_outgoing_count', 'f_call:phone_calls_rapids_outgoing_distinctcontacts',
      'f_call:phone_calls_rapids_outgoing_sumduration', is_sensitive], include_device_type: false,
    use_norm_features: false}, model_params: {arm_thresholds: {weekday: {afternoon: {
          conf: 0.125, supp: 0.125}, evening: {conf: 0.125, supp: 0.125}, morning: {
          conf: 0.125, supp: 0.125}, night: {conf: 0.125, supp: 0.125}}, weekend: {
        afternoon: {conf: 0.125, supp: 0.125}, evening: {conf: 0.125, supp: 0.125},
        morning: {conf: 0.125, supp: 0.125}, night: {conf: 0.125, supp: 0.125}}},
    arm_thresholds_memory_safe: {weekday: {afternoon: {conf: 0.2, supp: 0.2}, evening: {
          conf: 0.2, supp: 0.2}, morning: {conf: 0.2, supp: 0.2}, night: {conf: 0.2,
          supp: 0.2}}, weekend: {afternoon: {conf: 0.2, supp: 0.2}, evening: {conf: 0.2,
          supp: 0.2}, morning: {conf: 0.2, supp: 0.2}, night: {conf: 0.2, supp: 0.2}}},
    arm_thresholds_memory_safer: {weekday: {afternoon: {conf: 0.35, supp: 0.35}, evening: {
          conf: 0.35, supp: 0.35}, morning: {conf: 0.35, supp: 0.35}, night: {conf: 0.35,
          supp: 0.35}}, weekend: {afternoon: {conf: 0.35, supp: 0.35}, evening: {
          conf: 0.35, supp: 0.35}, morning: {conf: 0.35, supp: 0.35}, night: {conf: 0.35,
          supp: 0.35}}}, arm_thresholds_memory_safest: {weekday: {afternoon: {conf: 0.7,
          supp: 0.7}, evening: {conf: 0.7, supp: 0.7}, morning: {conf: 0.7, supp: 0.7},
        night: {conf: 0.9, supp: 0.9}}, weekend: {afternoon: {conf: 0.7, supp: 0.7},
        evening: {conf: 0.7, supp: 0.7}, morning: {conf: 0.8, supp: 0.8}, night: {
          conf: 0.9, supp: 0.9}}}, metric_w1: 1.0, metric_w2: 1.5, metric_w3: 0.5,
    num_top_rule: 10}, name: ml_xu_interpretable, training_params: {save_and_reload: false,
    verbose: 0}}
